//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMS_DBEntities : DbContext
    {
        public CMS_DBEntities()
            : base("name=CMS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Employee_Type> Employee_Type { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Logging_Details> Logging_Details { get; set; }
        public virtual DbSet<Manager_details> Manager_details { get; set; }
        public virtual DbSet<POS> POS { get; set; }
        public virtual DbSet<Product_Details> Product_Details { get; set; }
        public virtual DbSet<Product_Order> Product_Order { get; set; }
        public virtual DbSet<Purchase_Entry> Purchase_Entry { get; set; }
        public virtual DbSet<Purchase_Return> Purchase_Return { get; set; }
        public virtual DbSet<Salesman_Details> Salesman_Details { get; set; }
        public virtual DbSet<Supplier_Details> Supplier_Details { get; set; }
        public virtual DbSet<User_Details> User_Details { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Sales_Details> Sales_Details { get; set; }
    }
}
