//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Emp_ID { get; set; }
        public int ET_ID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public System.DateTime HireDate { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    
        public virtual Employee_Type Employee_Type { get; set; }
    }
}
