//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logging_Details
    {
        public int Sl { get; set; }
        public int User_Id { get; set; }
        public string User_Name { get; set; }
        public string User_Type { get; set; }
        public string Sign_In_Time { get; set; }
        public string Sign_Out_Type { get; set; }
    }
}
