//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager_details
    {
        public int MId { get; set; }
        public string MName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<int> Postal_code { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public Nullable<int> Commission { get; set; }
        public string Remarks { get; set; }
        public byte[] Image { get; set; }
    }
}
