//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Details
    {
        public int P_ID { get; set; }
        public string P_Name { get; set; }
        public string P_Category { get; set; }
        public string Description { get; set; }
        public double Purchase_Rate { get; set; }
        public double Sales_Rate { get; set; }
        public int Reorder_Point { get; set; }
        public int Purchase_Unit { get; set; }
        public int Stock { get; set; }
        public byte[] Image { get; set; }
    }
}
