//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Return
    {
        public int PRId { get; set; }
        public int PEId { get; set; }
        public int ReturnQuantity { get; set; }
    
        public virtual Purchase_Entry Purchase_Entry { get; set; }
    }
}
