//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Details
    {
        public int S_ID { get; set; }
        public string S_Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Postal_Code { get; set; }
        public string Contact { get; set; }
        public string Email_ID { get; set; }
        public string Remarks { get; set; }
        public string Acc_Name { get; set; }
        public string Acc_No { get; set; }
        public string Bank_Name { get; set; }
        public string Branch { get; set; }
    }
}
