//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Details
    {
        public int U_ID { get; set; }
        public string U_Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int User_Type { get; set; }
        public byte[] Image { get; set; }
    }
}
